Repository Whist-Team/Whist-Server, pull requests merged in 2022-09, with the labels that each got.

#339 FEATURE: HTTP Error Utility
  whist_server/api/room/action.py
  whist_server/api/room/info.py
  whist_server/api/room/join.py
  whist_server/api/room/trick.py
  whist_server/api/user/auth.py
  whist_server/api/user/create.py
  whist_server/api/util.py
Labels: enhancement

#337 FIX: use correct package name in test
  tests/whist_server/api/room/__init__.py
  tests/whist_server/api/room/base_created_case.py
  tests/whist_server/api/room/test_action.py
  tests/whist_server/api/room/test_create.py
  tests/whist_server/api/room/test_info.py
  tests/whist_server/api/room/test_join.py
  tests/whist_server/api/room/test_trick.py
Labels: tests

#338 ADD: Hand Notification
  tests/whist_server/api/room/test_game.py
  whist_server/__init__.py
  whist_server/api/room/game.py
  whist_server/database/room.py
  whist_server/web_socket/events/event.py
Labels: enhancement

#342 FEATURE: user info
  tests/whist_server/api/user/test_info.py
  whist_server/__init__.py
  whist_server/api/user/info.py
Labels: enhancement

#343 FEATURE: leave room
  tests/whist_server/api/room/test_join.py
  tests/whist_server/database/test_room.py
  whist_server/api/room/join.py
  whist_server/database/error.py
  whist_server/database/room.py
  whist_server/web_socket/events/event.py
Labels: enhancement

#345 TEST: cli
  tests/whist_server/test_cli.py
Labels: tests

#348 UPDATE: use list of player instead of number in list
  tests/whist_server/api/room/test_info.py
  tests/whist_server/database/test_room.py
  whist_server/database/room.py
Labels: enhancement

#355 Update deps
  poetry.lock
  pyproject.toml
Labels: dependencies

#356 REFACTOR: rename service test class
  tests/whist_server/services/test_room_db_service.py
Labels: tests
