Repository Whist-Team/Whist-Server, pull requests merged in 2022-06, with the labels that each got.

#219 Update action.py to have unready function
  tests/whist/server/api/game/test_action.py
  whist/server/api/game/action.py
  whist/server/services/error.py
Labels: enhancement

#227 FEATURE: Ranking Service
  tests/whist/server/api/ranking/__init__.py
  tests/whist/server/api/ranking/test_leaderboard.py
  tests/whist/server/base_user_test_case.py
  tests/whist/server/services/test_ranking_service.py
  tests/whist/server/services/test_user_db_service.py
  whist/server/__init__.py
  whist/server/api/ranking/__init__.py
  whist/server/api/ranking/leaderboard.py
  whist/server/services/ranking_service.py
Labels: enhancement

#233 REMOVE: no longer needed requirement [typing-extensions]
  requirements/requirements.txt
Labels: dependencies

#220 ADD: stale workflow
  .github/workflows/stale.yml
Labels: github_actions

#237 BUMP: code ql workflow's dependencies
  .github/workflows/codeql-analysis.yml
Labels: CI, dependencies, github_actions

#232 FEATURE: Side Channel
  tests/whist/server/api/game/base_created_case.py
  tests/whist/server/api/game/test_create.py
  tests/whist/server/base_token_case.py
  tests/whist/server/web_socket/__init__.py
  tests/whist/server/web_socket/test_entry.py
  tests/whist/server/web_socket/test_side_channel.py
  tests/whist/server/web_socket/test_subscriber.py
  whist/server/__init__.py
  whist/server/database/game.py
  whist/server/web_socket/__init__.py
  whist/server/web_socket/entry.py
  whist/server/web_socket/events/__init__.py
  whist/server/web_socket/events/event.py
  whist/server/web_socket/side_channel.py
  whist/server/web_socket/subscriber.py
Labels: enhancement

#239 FEATURE: events and wrapper
  tests/whist/server/web_socket/test_event.py
  tests/whist/server/web_socket/test_side_channel.py
  tests/whist/server/web_socket/test_subscriber.py
  whist/server/web_socket/events/event.py
  whist/server/web_socket/subscriber.py
Labels: enhancement

#244 FIX: ws entry joined error
  tests/whist/server/database/test_game.py
  tests/whist/server/web_socket/test_entry.py
  whist/server/database/game.py
  whist/server/web_socket/entry.py
Labels: bug

#254 Fix CLI starter and add docker-compose for dev
  docker-compose-dev.yml
  docker-compose.yml
  setup.py
  whist/server/__main__.py
  whist/server/cli.py
  whist/server/const.py
Labels: bug, enhancement

#256 Fix typo and wrong assumption in CLI code
  whist/server/__main__.py
  whist/server/cli.py
  whist/server/database/connection.py
Labels: bug

#262 FIX: secure routes
  tests/whist/server/api/game/test_info.py
  tests/whist/server/api/game/test_join.py
  tests/whist/server/api/ranking/test_leaderboard.py
  tests/whist/server/base_token_case.py
  whist/server/api/game/info.py
  whist/server/api/ranking/leaderboard.py
Labels: bug

#265 FIX: join room with no password
  .github/workflows/python-app.yml
  tests/whist/server/api/game/test_join.py
  whist/server/api/game/join.py
Labels: bug

#266 Misc fixes
  tests/whist/server/api/game/test_create.py
  tests/whist/server/api/game/test_join.py
  tests/whist/server/api/user/test_auth.py
  tests/whist/server/api/user/test_create.py
  tests/whist/server/base_token_case.py
  whist/server/api/game/action.py
  whist/server/api/game/create.py
  whist/server/api/game/info.py
  whist/server/api/game/join.py
  whist/server/api/game/trick.py
  whist/server/api/user/auth.py
  whist/server/api/user/create.py
  whist/server/database/access_token.py
  whist/server/database/game.py
  whist/server/services/authentication.py
  whist/server/services/game_db_service.py
Labels: bug

#252 FEATURE: channel service
  tests/whist/server/api/game/test_join.py
  tests/whist/server/base_token_case.py
  tests/whist/server/services/test_channel_service.py
  tests/whist/server/web_socket/test_entry.py
  tests/whist/server/web_socket/test_notification.py
  tests/whist/server/web_socket/test_side_channel.py
  tests/whist/server/web_socket/test_subscriber.py
  whist/server/api/game/create.py
  whist/server/api/game/join.py
  whist/server/database/game.py
  whist/server/services/channel_service.py
  whist/server/services/error.py
  whist/server/web_socket/entry.py
  whist/server/web_socket/side_channel.py
  whist/server/web_socket/subscriber.py
Labels: enhancement

#268 ADD: more notification
  tests/whist/server/web_socket/test_notification.py
  whist/server/api/game/action.py
  whist/server/api/game/trick.py
Labels: enhancement

#269 ADD: favicon
  static/ace-of-spades-icon-17.jpg
  tests/whist/server/api/test_index.py
  whist/server/api/api.py
Labels: enhancement

#271 Add cors headers
  whist/server/__init__.py
Labels: bug

#270 UPDATE: whist-core to v0.2.0 and breaking changes adaption
  requirements/requirements.txt
  tests/whist/server/services/test_game_db_service.py
  whist/server/api/game/action.py
  whist/server/database/game.py
Labels: dependencies

#275 UDPATE: disable fail fast for lint
  .github/workflows/pylint.yml
Labels: CI, github_actions

#274 FEATURE: Trick Done Notification
  tests/whist/server/api/game/test_trick.py
  tests/whist/server/database/test_game.py
  tests/whist/server/web_socket/test_notification.py
  whist/server/api/game/trick.py
  whist/server/database/game.py
  whist/server/web_socket/events/event.py
Labels: enhancement
