Repository Whist-Team/Whist-Server, pull requests merged in 2022-11, with the labels that each got.

#368 FEATURE: next trick
  tests/whist_server/api/room/test_game.py
  tests/whist_server/api/room/test_trick.py
  whist_server/api/room/game.py
  whist_server/web_socket/events/event.py
Labels: bug, enhancement

#385 UPDATE: replace passlib with bcrypt
  poetry.lock
  pyproject.toml
  tests/whist_server/services/test_password.py
  whist_server/database/room.py
  whist_server/database/user.py
  whist_server/services/password.py
Labels: dependencies, python

#388 Update deps
  poetry.lock
  pyproject.toml
Labels: dependencies

#393 UPDATE: replace python-jose with pyjwt
  poetry.lock
  pyproject.toml
  whist_server/services/authentication.py
Labels: dependencies, python

#377 FIX: min max player in room
  poetry.lock
  pyproject.toml
  tests/whist_server/api/room/test_create.py
  tests/whist_server/database/test_room.py
  tests/whist_server/services/test_room_db_service.py
  whist_server/api/room/action.py
  whist_server/api/room/create.py
  whist_server/database/room.py
Labels: bug

#401 update deps and bump version to 0.6.0
  poetry.lock
  pyproject.toml
  whist_server/__init__.py
Labels: dependencies
